name: Publish new release

on:
  workflow_dispatch:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Create packages
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: >-
           dotnet build 
           --configuration Release 
           --no-restore  
           -p:Version=${VERSION} 
           --warnaserror
    - name: Test
      run: >-
           dotnet test
           --configuration Release 
           --no-build
           -p:Version=${VERSION} 
    - name: Pack
      run: >-
           dotnet pack
           --configuration Release
           --no-build
           --output "${GITHUB_WORKSPACE}/artifacts"
           -p:Version=${VERSION}
           -p:RepositoryUrl="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
           -p:RepositoryType=git
           -p:RepositoryBranch="${GITHUB_REF}"
    - name: Push
      run: >-
           dotnet nuget 
           push ${GITHUB_WORKSPACE}/artifacts/*.nupkg
           --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json 
           --api-key ${{ github.token }}
